"""feat(venue): add venue domain models

Revision ID: 9170dab48e33
Revises: 0003
Create Date: 2026-06-05 15:14:00.136309

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9170dab48e33'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue_type', sa.Text(), nullable=False),
    sa.Column('address_line1', sa.Text(), nullable=False),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), server_default=sa.text("'India'"), nullable=False),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.Column('min_capacity', sa.Integer(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('spans_next_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allowed_booking_types', postgresql.ARRAY(sa.Text()), server_default=sa.text("ARRAY['full_day','time_slot']"), nullable=False),
    sa.Column('min_booking_duration_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('max_booking_duration_minutes', sa.Integer(), server_default='1440', nullable=False),
    sa.Column('slot_interval_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('pre_buffer_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('post_buffer_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pricing_mode', sa.Text(), server_default=sa.text("'flat'"), nullable=False),
    sa.Column('base_price_paise', sa.BigInteger(), nullable=True),
    sa.Column('hourly_rate_paise', sa.BigInteger(), nullable=True),
    sa.Column('platform_commission_pct', sa.Numeric(precision=5, scale=2), server_default='10.00', nullable=False),
    sa.Column('advance_pct', sa.Numeric(precision=5, scale=2), server_default='30.00', nullable=False),
    sa.Column('balance_due_days_before_event', sa.Integer(), server_default='7', nullable=False),
    sa.Column('owner_action_window_hours', sa.Integer(), server_default='48', nullable=False),
    sa.Column('overdue_advance_refund_pct', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'suspended', name='venue_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pricing_mode IN ('flat', 'hourly')", name='ck_venues_pricing_mode'),
    sa.CheckConstraint('advance_pct > 0 AND advance_pct <= 100', name='ck_venues_advance_pct'),
    sa.CheckConstraint('balance_due_days_before_event > 0', name='ck_venues_balance_days'),
    sa.CheckConstraint('base_price_paise >= 0', name='ck_venues_base_price'),
    sa.CheckConstraint('hourly_rate_paise >= 0', name='ck_venues_hourly_rate'),
    sa.CheckConstraint('max_booking_duration_minutes > 0', name='ck_venues_max_duration'),
    sa.CheckConstraint('max_capacity > 0', name='ck_venues_max_capacity'),
    sa.CheckConstraint('min_booking_duration_minutes <= max_booking_duration_minutes', name='ck_venues_duration_range'),
    sa.CheckConstraint('min_booking_duration_minutes > 0', name='ck_venues_min_duration'),
    sa.CheckConstraint('min_capacity > 0', name='ck_venues_min_capacity'),
    sa.CheckConstraint('min_capacity IS NULL OR min_capacity <= max_capacity', name='ck_venues_capacity'),
    sa.CheckConstraint('overdue_advance_refund_pct BETWEEN 0 AND 100', name='ck_venues_overdue_refund_pct'),
    sa.CheckConstraint('owner_action_window_hours BETWEEN 24 AND 72', name='ck_venues_action_window'),
    sa.CheckConstraint('platform_commission_pct >= 0 AND platform_commission_pct <= 100', name='ck_venues_commission'),
    sa.CheckConstraint('post_buffer_minutes >= 0', name='ck_venues_post_buffer'),
    sa.CheckConstraint('pre_buffer_minutes >= 0', name='ck_venues_pre_buffer'),
    sa.CheckConstraint('slot_interval_minutes > 0', name='ck_venues_slot_interval'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_venues_search', 'venues', ['city', 'venue_type', 'status', 'is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('venue_amenities',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('amenity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'amenity_id')
    )
    op.create_table('venue_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('spans_next_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_venue_availability_day'),
    sa.CheckConstraint('is_available = false OR (opens_at IS NOT NULL AND closes_at IS NOT NULL)', name='ck_venue_availability_times'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('venue_availability_unique_day', 'venue_availability', ['venue_id', 'day_of_week'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('venue_blocked_dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_venue_blocked_dates_order'),
    sa.ForeignKeyConstraint(['blocked_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_venue_blocked_dates_venue', 'venue_blocked_dates', ['venue_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('venue_cancellation_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('tier_1_hours', sa.Integer(), nullable=True),
    sa.Column('tier_1_refund_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tier_2_hours', sa.Integer(), nullable=True),
    sa.Column('tier_2_refund_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tier_3_hours', sa.Integer(), nullable=True),
    sa.Column('tier_3_refund_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('no_show_refund_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('platform_fee_refundable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(tier_1_hours IS NULL OR tier_2_hours IS NULL OR tier_1_hours > tier_2_hours) AND (tier_2_hours IS NULL OR tier_3_hours IS NULL OR tier_2_hours > tier_3_hours)', name='tiers_descending'),
    sa.CheckConstraint('(tier_1_hours IS NULL) = (tier_1_refund_pct IS NULL)', name='tier_1_paired'),
    sa.CheckConstraint('(tier_2_hours IS NULL) = (tier_2_refund_pct IS NULL)', name='tier_2_paired'),
    sa.CheckConstraint('(tier_3_hours IS NULL) = (tier_3_refund_pct IS NULL)', name='tier_3_paired'),
    sa.CheckConstraint('no_show_refund_pct BETWEEN 0 AND 100', name='ck_vcp_no_show_pct'),
    sa.CheckConstraint('tier_1_hours > 0', name='ck_vcp_tier_1_hours'),
    sa.CheckConstraint('tier_1_refund_pct BETWEEN 0 AND 100', name='ck_vcp_tier_1_pct'),
    sa.CheckConstraint('tier_2_hours > 0', name='ck_vcp_tier_2_hours'),
    sa.CheckConstraint('tier_2_refund_pct BETWEEN 0 AND 100', name='ck_vcp_tier_2_pct'),
    sa.CheckConstraint('tier_3_hours > 0', name='ck_vcp_tier_3_hours'),
    sa.CheckConstraint('tier_3_refund_pct BETWEEN 0 AND 100', name='ck_vcp_tier_3_pct'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id')
    )
    op.create_table('venue_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_cover', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('venue_photos_one_cover', 'venue_photos', ['venue_id'], unique=True, postgresql_where=sa.text('is_cover = true AND deleted_at IS NULL'))

    
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN NEW.updated_at = now(); RETURN NEW; END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trg_venues_updated_at
        BEFORE UPDATE ON venues
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    """)
    
    op.execute("""
        CREATE TRIGGER trg_venue_availability_updated_at
        BEFORE UPDATE ON venue_availability
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    """)
    
    op.execute("""
        CREATE TRIGGER trg_venue_cancellation_policies_updated_at
        BEFORE UPDATE ON venue_cancellation_policies
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('venue_photos_one_cover', table_name='venue_photos', postgresql_where=sa.text('is_cover = true AND deleted_at IS NULL'))
    op.drop_table('venue_photos')
    op.drop_table('venue_cancellation_policies')
    op.drop_index('idx_venue_blocked_dates_venue', table_name='venue_blocked_dates', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('venue_blocked_dates')
    op.drop_index('venue_availability_unique_day', table_name='venue_availability', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('venue_availability')
    op.drop_table('venue_amenities')
    op.drop_index('idx_venues_search', table_name='venues', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('venues')
    op.drop_table('amenities')
    # ### end Alembic commands ###
