"""booking_schema

Revision ID: 0c70837a672c
Revises: 9170dab48e33
Create Date: 2026-06-06 12:09:27.541886

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0c70837a672c'
down_revision: Union[str, None] = '9170dab48e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_type', sa.Enum('full_day', 'time_slot', name='booking_type'), nullable=False),
    sa.Column('status', sa.Enum('requested', 'owner_accepted', 'confirmed', 'completed', 'hold_expired', 'request_expired', 'conflict_cancelled', 'user_cancelled', 'admin_cancelled', 'owner_rejected', 'balance_overdue_cancelled', name='booking_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'advance_paid', 'fully_paid', 'refunded', 'partially_refunded', name='payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
