"""Change of schema name from base_price_paise to starting_price_paise

Revision ID: 3dce944fa4c3
Revises: 108e5e92fd6e
Create Date: 2026-06-14 11:18:46.922131

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3dce944fa4c3'
down_revision: Union[str, None] = '108e5e92fd6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('starting_price_paise', sa.BigInteger(), nullable=True))
    op.drop_column('venues', 'base_price_paise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('base_price_paise', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('venues', 'starting_price_paise')
    # ### end Alembic commands ###
