"""Add last_completed_step to Venue

Revision ID: 523613d60f75
Revises: 23f89ef3a202
Create Date: 2026-06-21 20:36:07.394084

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '523613d60f75'
down_revision: Union[str, None] = '23f89ef3a202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('last_completed_step', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'last_completed_step')
    # ### end Alembic commands ###
