"""payment and booking schema code update to latest

Revision ID: 56b83e0f7f4a
Revises: ec2964b424ff
Create Date: 2026-06-20 13:38:01.667480

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '56b83e0f7f4a'
down_revision: Union[str, None] = 'ec2964b424ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
