"""venue category table

Revision ID: 6dadfa890c15
Revises: 108e5e92fd6e
Create Date: 2026-06-18 22:07:44.130306

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6dadfa890c15'
down_revision: Union[str, None] = '108e5e92fd6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('banner_image', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_venue_categories_slug_active', 'venue_categories', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('venues', sa.Column('category_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_venues_search'), table_name='venues', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_venues_search', 'venues', ['city', 'category_id', 'status', 'is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_foreign_key(None, 'venues', 'venue_categories', ['category_id'], ['id'])
    op.drop_column('venues', 'venue_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('venue_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_index('idx_venues_search', table_name='venues', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('idx_venues_search'), 'venues', ['city', 'venue_type', 'status', 'is_active'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('venues', 'category_id')
    op.drop_index('uq_venue_categories_slug_active', table_name='venue_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('venue_categories')
    # ### end Alembic commands ###
