"""search index table + venue table column update

Revision ID: adc8fe218fd7
Revises: 004b8919fa8e
Create Date: 2026-06-30 21:45:29.148213

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

revision: str = 'adc8fe218fd7'
down_revision: Union[str, None] = '004b8919fa8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'payment_mode')
    op.add_column('venues', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.add_column('venues', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.add_column('venues', sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('venues', 'payment_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('payment_mode', sa.TEXT(), server_default=sa.text("'advance_balance'::text"), autoincrement=False, nullable=False))
    op.drop_column('venues', 'embedding_updated_at')
    op.drop_column('venues', 'embedding')
    op.drop_column('venues', 'search_vector')
    op.add_column('bookings', sa.Column('payment_mode', sa.VARCHAR(), server_default=sa.text("'advance_balance'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
