"""amenity name uniqueness: partial index excluding soft-deleted rows

Revision ID: bf6b28a6d1fd
Revises: 914d6f7a8b9c
Create Date: 2026-06-09 18:47:52.686325

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bf6b28a6d1fd'
down_revision: Union[str, None] = '914d6f7a8b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('amenities_name_key'), 'amenities', type_='unique')
    op.create_index('uq_amenities_name_active', 'amenities', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_amenities_name_active', table_name='amenities', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('amenities_name_key'), 'amenities', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
