"""Bugs and Balance payment refactor

Revision ID: da3ff47ffce8
Revises: ec2964b424ff
Create Date: 2026-06-21 10:00:05.418688

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'da3ff47ffce8'
down_revision: Union[str, None] = 'ec2964b424ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_mode', sa.String(), server_default='advance_balance', nullable=False))
    op.add_column('payments', sa.Column('payment_type', sa.String(), server_default='advance', nullable=False))
    op.add_column('venues', sa.Column('payment_mode', sa.Text(), server_default='advance_balance', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'payment_mode')
    op.drop_column('payments', 'payment_type')
    op.drop_column('bookings', 'payment_mode')
    # ### end Alembic commands ###
