"""venue category_id not null

Revision ID: ec2964b424ff
Revises: 6dadfa890c15
Create Date: 2026-06-18 22:41:20.323502

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ec2964b424ff'
down_revision: Union[str, None] = '6dadfa890c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
